zippick/build.gradle
zippick/src/main/java/zippick/global/config/OpenApiConfig.java
zippick/src/main/resources/application.yml
zippick/src/main/resources/mapper/Mapper.xml
zippick/src/test/java/zippick/S3UploadTest.java

#10 
- yml, gradle에서 발생하는 의존성 등 문제 해결
- 충돌 해결

Refactor : 충돌해결관련

---

.github/workflows/deploy.yml
zippick/build.gradle
zippick/src/main/java/zippick/domain/member/controller/MemberController.java
zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java
zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
zippick/src/main/java/zippick/domain/member/service/MemberService.java
zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
zippick/src/main/java/zippick/domain/product/controller/ProductController.java
zippick/src/main/java/zippick/domain/product/dto/request/AiComposeRequest.java
zippick/src/main/java/zippick/domain/product/dto/response/AiComposeResponse.java
zippick/src/main/java/zippick/domain/product/dto/response/ProductDto.java
zippick/src/main/java/zippick/domain/product/dto/response/ProductResponse.java
zippick/src/main/java/zippick/domain/product/mapper/ProductMapper.java
zippick/src/main/java/zippick/domain/product/model/FurnitureCategory.java
zippick/src/main/java/zippick/domain/product/service/ProductService.java
zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
zippick/src/main/java/zippick/global/config/CorsConfig.java
zippick/src/main/java/zippick/global/config/OpenApiConfig.java
zippick/src/main/java/zippick/global/config/S3Config.java
zippick/src/main/java/zippick/global/exception/ErrorCode.java
zippick/src/main/java/zippick/infra/file/s3/S3Uploader.java
zippick/src/main/java/zippick/member/service/MemberService.java
zippick/src/main/resources/application.yml
zippick/src/main/resources/mapper/member/MemberMapper.xml
zippick/src/main/resources/mapper/product/ProductMapper.xml
zippick/src/test/java/zippick/S3UploadTest.java

#4 
- AI 가구 배치 API 구현
- 방 내부 사진(file)과 의자 사진url를 받아 AI 합성 후 결과 반환
- 방 내부 사진은 s3에 자동 업로드되며 결과 사진은 약 1시간 정도 유효
- 상품명으로 목록 조회 API 구현
- 사이즈 기반(width, depth, height) 목록 조회 API 구현
<br>
<br>
<br>

feat : AI 합성 및 Product 조회 관련 API

---

zippick/build.gradle
zippick/src/main/java/zippick/domain/auth/controller/AuthController.java
zippick/src/main/java/zippick/domain/auth/dto/AuthTokenDTO.java
zippick/src/main/java/zippick/domain/auth/dto/request/LoginRequest.java
zippick/src/main/java/zippick/domain/auth/dto/response/LoginResponse.java
zippick/src/main/java/zippick/domain/auth/mapper/AuthMapper.java
zippick/src/main/java/zippick/domain/auth/service/AuthService.java
zippick/src/main/java/zippick/domain/auth/service/AuthServiceImpl.java
zippick/src/main/java/zippick/domain/member/controller/MemberController.java
zippick/src/main/java/zippick/domain/member/dto/MemberDTO.java
zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java
zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
zippick/src/main/java/zippick/domain/member/service/MemberService.java
zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
zippick/src/main/java/zippick/global/config/FilterConfig.java
zippick/src/main/java/zippick/global/config/SecurityConfig.java
zippick/src/main/java/zippick/global/filter/AuthTokenFilter.java
zippick/src/main/resources/mapper/auth/AuthMapper.xml

feat: 로그인 로그아웃 필터

---

zippick/src/main/java/zippick/global/config/OpenApiConfig.java

[FEAT] 스웨거 인증 추가

---

zippick/src/main/java/zippick/domain/member/controller/MemberController.java
zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java
zippick/src/main/java/zippick/domain/member/dto/response/MyInfoResponse.java
zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
zippick/src/main/java/zippick/domain/member/service/MemberService.java
zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
zippick/src/main/java/zippick/global/exception/ErrorCode.java
zippick/src/main/java/zippick/global/filter/AuthTokenFilter.java
zippick/src/main/resources/mapper/member/MemberMapper.xml

feat: 내 정보 조회

---

zippick/src/main/java/zippick/domain/product/controller/ProductController.java
zippick/src/main/java/zippick/domain/product/mapper/ProductMapper.java
zippick/src/main/java/zippick/domain/product/service/ProductService.java
zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
zippick/src/main/resources/mapper/product/ProductMapper.xml

#27 
- 사이즈 기반 가구 검색시에 요청인자에 카테고리를 받게했습니다.
- api명세서도 함께 수정했습니다.

[REFACTOR] 사이즈 기반 검색시 카테고리 추가

---

zippick/src/main/java/zippick/domain/member/controller/MemberController.java
zippick/src/main/java/zippick/domain/member/mapper/MemberMapper.java
zippick/src/main/java/zippick/domain/member/service/MemberService.java
zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java
zippick/src/main/java/zippick/global/filter/AuthTokenFilter.java
zippick/src/main/resources/mapper/member/MemberMapper.xml

feat: 이메일 중복 확인

---

zippick/src/main/java/zippick/domain/product/controller/ProductController.java
zippick/src/main/java/zippick/domain/product/dto/ProductDto.java
zippick/src/main/java/zippick/domain/product/dto/ProductLikedDto.java
zippick/src/main/java/zippick/domain/product/dto/request/LikedRequest.java
zippick/src/main/java/zippick/domain/product/dto/response/ProductDetailResponse.java
zippick/src/main/java/zippick/domain/product/dto/response/ProductResponse.java
zippick/src/main/java/zippick/domain/product/mapper/ProductMapper.java
zippick/src/main/java/zippick/domain/product/service/ProductService.java
zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
zippick/src/main/java/zippick/global/exception/ErrorCode.java
zippick/src/main/java/zippick/global/filter/AuthTokenFilter.java
zippick/src/main/resources/mapper/product/ProductMapper.xml

상품 상세 조회 및 찜 목록 조회

---

zippick/src/main/java/zippick/domain/product/controller/ProductController.java
zippick/src/main/java/zippick/domain/product/dto/response/InteriorAnalysisResponse.java
zippick/src/main/java/zippick/domain/product/service/ProductService.java
zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java

[FEAT] AI 기반 이미지 분석 구현

---

zippick/src/main/java/zippick/domain/product/dto/response/InteriorAnalysisResponse.java
zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java

AI 기반 이미지 분석 프롬프트 수정

---

.github/workflows/deploy.yml

#48 
cicd관련 간단한 스크립트 수정이 있어서 재배포합니다.

[REFACTOR] cicd workflow 수정

---

.github/workflows/deploy.yml
zippick/src/main/java/zippick/global/config/OpenApiConfig.java
zippick/src/main/java/zippick/global/config/S3Config.java

[DEPLOY] 재배포

---

zippick/src/main/java/zippick/domain/product/controller/ProductController.java
zippick/src/main/java/zippick/domain/product/dto/request/AiRecommendRequest.java
zippick/src/main/java/zippick/domain/product/mapper/ProductMapper.java
zippick/src/main/java/zippick/domain/product/service/ProductService.java
zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java
zippick/src/main/resources/mapper/product/ProductMapper.xml

이미지 분석 기반 상품 필터링 구현

---

zippick/src/main/java/zippick/domain/member/service/MemberServiceImpl.java

refactor: 회원가입 트랜젝션 설정

---

zippick/src/main/java/zippick/domain/member/dto/request/SignUpRequest.java

bug: 데이터 타입 수정

---

zippick/src/main/java/zippick/domain/product/model/FurnitureCategory.java

[FIX] 카테고리 오타 수정

---

zippick/src/main/resources/mapper/notification/NotificationMapper.xml
zippick/src/main/resources/mapper/product/ProductMapper.xml

[REFACTOR] 불필요한 offset제거

---

zippick/src/main/java/zippick/domain/product/controller/ProductController.java

[FIX] 상품조회 긴급수정

---

zippick/src/main/java/zippick/domain/notification/controller/NotificationController.java
zippick/src/main/java/zippick/domain/notification/mapper/NotificationMapper.java
zippick/src/main/java/zippick/domain/notification/service/NotificationService.java
zippick/src/main/java/zippick/domain/notification/service/NotificationServiceImpl.java

[FIX] 불필요한offset 제거

---

zippick/src/main/resources/mapper/order/OrderMapper.xml

[FIX] 이미지 버그 수정

---

zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java

[REFACTOR] 프롬프트 조정

---

zippick/src/main/java/zippick/domain/product/service/ProductServiceImpl.java

프롬프트 개선 후 배포
